# Generated by Django 3.1.2 on 2020-10-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec', models.ImageField(upload_to='')),
                ('time', models.TimeField(auto_now_add=True)),
                ('prediction', models.CharField(max_length=20)),
                ('actual', models.CharField(max_length=20)),
                ('accuracy', models.FloatField()),
            ],
        ),
    ]
