# Generated by Django 3.1.2 on 2020-10-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='accuracy',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='actual',
        ),
    ]
