# Generated by Django 3.1.2 on 2020-10-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201024_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='spec',
        ),
    ]
