# Generated by Django 3.1.2 on 2020-10-24 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201024_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(null=True, upload_to='audio'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='utime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
