# Generated by Django 3.1.2 on 2020-10-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201024_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='spec',
            field=models.ImageField(null=True, upload_to='spectrogram'),
        ),
    ]
